stages:
  split:
    cmd: python src/split/data_split.py
    deps:
    - data/raw
    - src/split/data_split.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize:
    cmd: python src/normalize/normalize.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/normalize/normalize.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  gridsearch:
    cmd: python src/gridsearch/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/gridsearch/grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python src/train/train.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/best_params.pkl
    - src/train/train.py
    outs:
    - models/lr_model.pkl
  predict:
    cmd: python src/evaluate/evaluate.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/lr_model.pkl
    - src/evaluate/evaluate.py
    outs:
    - data/predictions.csv
    metrics:
    - metrics/scores.json
